name: Docker Build
on:
  push:
    branches:
      [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      # 1.檢出代碼
      - name: Check out code
        uses: actions/checkout@v2


      # 2.設置JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      # 3.構建專案
      - name: Build project
        run: mvn clean package
        
      # 4.登入docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 5. 構建 Docker image
#      - name: Build Docker Image
#        run: docker build -t cicd:latest .