name: Docker Build
on:
  push:
    branches:
      [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest
    # 針對不同環境去做CI以及獲取 secrets, 目前設定環境是Dev
    environment: Dev
    steps:
      # 1.檢出代碼
      - name: Check out code
        uses: actions/checkout@v2


      # 2.設置JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      # 3.構建專案
      - name: Build project
        run: mvn clean package
        
      # 列出檔案
#      - name: list file
#        run: ls -al target
        
      # 4.登入docker hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 5. 構建 Docker image
      - name: Build Docker Image
        run: docker build -t cicd:latest -f ./DockerFile .
      # 5.5 將 docker image 加上 tag
      - name: tag docker image
        run: docker tag cicd:latest herry505/testrepo:latest
        
      # 6. 將 Docker image push 到 Docker repo 測試
      - name: Push Image To Docker hub
        run: docker push herry505/testrepo:latest

